name: cpp-linter

on:
    push:
        paths-ignore: "docs/**"
    pull_request:
        paths-ignore: "docs/**"

jobs:
    cpp-linter:
        strategy:
            matrix:
                os:
                    - ubuntu
                    - macos
                    - windows
        runs-on: ${{matrix.os}}-latest
        steps:
            - uses: actions/checkout@v4
            - name: Print info
              run: |
                  echo "Running on ${{ matrix.os }}"
            - uses: ./ # uses action.yml in the root directory
              id: linter
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  style: file
                  files-changed-only: false
                  database: ${{github.workspace}}/demo/
            - name: Fail fast?!
              if: steps.linter.outputs.checks-failed != 0
              run: |
                  echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
